[package]
name = "demoserver"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
axum = "0.8.1"
log = "0.4.27"
serde = "1.0.218"
serde_json = "1.0.139"
stderrlog = "0.6.0"
terralib = {path = "../terralib"}
tokio = { version = "1.43.0", features = ["full"] }
