name: Build CAD

on: push
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5.5.0
      with:
        python-version: "3.13"
        cache: 'pip'

    - name: add kicad ppa
      run: |
        sudo add-apt-repository --yes ppa:kicad/kicad-9.0-releases
        sudo apt-get update
    - name: install apt packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: make cmake cargo kicad pkg-config fontconfig
        version: 1.6

    - name: install python deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: instantiate git submodules
      run: git submodule update --init

    - name: render cad outputs
      run: make cadquery

    - name: save artifacts
      uses: actions/upload-artifact@v4
      with:
        path: build
