name: Build CAD

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5.5.0
      with:
        python-version: "3.13"
        cache: 'pip'

    # Note: this workflow is for the cad models, but we still need kicad in
    # order to generate 3d models of the circuit boards.
    - name: add kicad ppa
      run: |
        sudo add-apt-repository --yes ppa:kicad/kicad-9.0-releases
        sudo apt-get update
    - name: install apt packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: make kicad pkg-config fontconfig
        version: 1.6

    - name: install python deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: render cad outputs
      run: make cadquery

    - name: save artifacts
      uses: actions/upload-artifact@v4
      with:
        path: build
