name: Electronics

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: add kicad ppa
      run: |
        sudo add-apt-repository --yes ppa:kicad/kicad-9.0-releases
        sudo apt-get update
    - name: install apt packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: kicad

    - name: build pcb outputs
      run: make pcb

    - name: save artifacts
      uses: actions/upload-artifact@v4
      with:
        path: build/pcb
